---
title: "figures"
output: html_document
---
These are figures for simpimp CogSci 2015.

Read file:

```{r}
rm(list = ls())
source("../analysis/helpers/useful.R")
source("../analysis/helpers/et_helper.R")
library(dplyr)

# read data
d <- read.csv("../data/simpimp_0pros-short.csv")
```



```{r}
subsample.hz <- 30 # 10 hz is decent, eventually we should set to 30 or 60 hz
d$t.crit.binned <- round(d$t.crit*subsample.hz)/subsample.hz # subsample step
```

## Expt 1: correct ~ t.crit.binned + trial_type + subid + age_group

```{r}
mss <- aggregate(correct ~ t.crit.binned + trial_type + subid + age_group, 
                 subset(d, expt == "1"), mean)
ms <- aggregate(correct ~ t.crit.binned + trial_type + age_group, mss, mean)

ggplot(ms, aes(x = t.crit.binned, y = correct, colour = age_group)) +
  geom_line() +
  facet_wrap(~ trial_type) + 
  geom_hline(yintercept=.50,lty=4) + 
  geom_vline(xintercept=.78,lty=3) +   
  geom_vline(xintercept=0,lty=3) + 
  xlab("Time (s)") + ylab("Proportion correct looking") + 
  scale_x_continuous(limits=c(-1,3.3),expand = c(0,0)) + 
  scale_y_continuous(limits=c(0,1),expand = c(0,0))
```

## Expt 1: reaction time

```{r}
library(directlabels)
d1_1 <- read.csv("../data/simpimp_0pros_rt.csv")

# aggregate t.crit.binned ~ age_group + trial_type
ms <- aggregate(t.crit.binned ~ age_group + trial_type,
                  data = d1_1, mean)
mss <- aggregate(t.crit.binned ~ age_group + trial_type + subid, data = d1_1, mean)
ms$cih <- aggregate(t.crit.binned ~ age_group + trial_type, mss, ci.high)$t.crit.binned
ms$cil <- aggregate(t.crit.binned ~ age_group + trial_type, mss, ci.low)$t.crit.binned

levels(ms$trial_type) <- c("Control-double", "Control-single", "Inference")
#plot
direct.label(qplot(age_group, t.crit.binned, group=trial_type, label=trial_type,
      colour=trial_type, 
      geom="line",
      data=subset(ms, age_group != "adult")) +
    geom_linerange(aes(ymin=t.crit.binned-cil,ymax=t.crit.binned+cih,width=.2),
                  position=position_dodge(width=.1)) + 
  ylab("Reaction Time (s)") + 
  xlab("Age group"), "chull.grid")

```

## Expt 1: Dwell time
```{r}
# by age
window <- c(1.5,4)
mss <- aggregate(correct ~ trial_type + age_group + subid, 
                subset(d,t.crit.binned > window[1] & t.crit.binned < window[2] & expt == "1"), 
                       mean)
ms <- aggregate(correct ~ trial_type + age_group, mss, mean)
ms$cih <- aggregate(correct ~ trial_type + age_group, mss, ci.high)$correct
ms$cil <- aggregate(correct ~ trial_type + age_group, mss, ci.low)$correct

quartz()
qplot(age_group,correct,
      fill=age_group, stat="identity",
      geom="bar",ylim=c(0,1),
      data=subset(ms, age_group != "1")) + 
  ylab("Proportion correct looking") + 
  geom_hline(yintercept=.50,lty=4) + 
  facet_wrap(~trial_type) + 
  geom_errorbar(aes(ymin=correct-cil,ymax=correct+cih,width=.2)) 
```



## Expt 2: correct ~ t.crit.binned + trial_type + subid + age_group

```{r}
mss <- d %>%
  filter(age_group == "3" | age_group == "4") %>%
  filter(t.crit > 1 & t.crit <= 4.2) %>%
  mutate(window = ifelse(t.crit > 1 & t.crit <= 2.6, "early", "late")) %>%
  group_by(expt, trial_type, age_group, window, subid) %>%
  summarise(correct = mean(correct, na.rm = TRUE))

ms <- aggregate(correct ~ expt + trial_type + window +  age_group, mss, mean)
ms$cih <- aggregate(correct ~ expt + trial_type + window +  age_group, mss, ci.high)$correct
ms$cil <- aggregate(correct ~ expt + trial_type + window +  age_group, mss, ci.low)$correct

ms$expt <- as.factor(ms$expt)
levels(ms$expt) <- c("Expt 1", "Expt 2")

ggplot(subset(ms, trial_type == "inf"), 
       aes(fill=expt, y=correct, x=window)) +
  geom_bar(position="dodge", stat="identity") + 
  facet_wrap(~age_group) +
  ylab("Proportion correct looking") + 
  guides(fill=guide_legend(title=NULL)) +
  theme(legend.position=c(.08, .9), 
        legend.key.size = unit(.25, "cm"),
        legend.text = element_text(size = 8)) +
  geom_hline(yintercept=.50,lty=4) + 
  geom_errorbar(aes(ymin=correct-cil,ymax=correct+cih,width=.2),position=position_dodge(width = 0.90))

```

## Expt 1 & 2: Compare line graphs

```{r}
mss <- d %>%
  filter(age_group == "3" | age_group == "4") %>%
  filter((expt == "1" & t.crit > -1 & t.crit <= 3.62) |
           (expt == "2" & t.crit > -1 & t.crit <= 4)) %>%
  filter(trial_type == "inf") %>%
  group_by(expt, trial_type, age_group, t.crit.binned, subid, item) %>%
  summarise(correct = mean(correct, na.rm = TRUE))

mss$subid <- factor(mss$subid)
mss$expt <- factor(mss$expt)
mss$age_group <- as.factor(mss$age_group) # age as factor
mss$trial_type <- relevel(mss$trial_type, "cs")

ms <- aggregate(correct ~ expt + t.crit.binned + trial_type + age_group, mss, mean)

ms$expt <- as.factor(ms$expt)
levels(ms$expt) <- c("Expt 1", "Expt 2")
levels(ms$age_group) <- c("2", "3-year-olds", "4-year-olds", "5", "adult")

p <- ggplot(subset(ms, trial_type == "inf"), aes(x = t.crit.binned, y = correct, colour = age_group)) +
  geom_line() +
  facet_grid(.~expt, scales = "free_x") +
  geom_vline(xintercept=0,lty=3) + 
  geom_hline(yintercept=.50,lty=4) + 
  theme(legend.position="none") +
  xlab("Time (s)") + ylab("Proportion correct looking") + 
  scale_x_continuous(expand = c(0,0)) + 
  scale_y_continuous(limits=c(0,1),expand = c(0,0)) +
  scale_colour_manual(values=c("#909000", "#18a860"))

vline.data <- data.frame(z = c(.78, 1.16), expt = c("Expt 1","Expt 2"))
vline.data2 <- data.frame(z = c(2.2, 2.58), expt = c("Expt 1","Expt 2"))
p + geom_vline(aes(xintercept = z), vline.data, lty=3) +
  geom_vline(aes(xintercept = z), vline.data2, lty=3) +
 geom_dl(aes(label=age_group),method="smart.grid")


```
