---
title: "simpimp_0pros-stat"
output: html_document
---

These are stats for simpimp CogSci 2015.

Read file:

```{r initial_setup}
rm(list = ls())
source("../analysis/helpers/useful.R")
source("../analysis/helpers/et_helper.R")
detach(package:plyr)
library(dplyr)

# read data
d <- read.csv("../data/simpimp_0pros-short.csv")
```

# Experiment 1

## lmer: effect of trial type and age on accuracy in Expt 1 (Table 1)

### Set up aggregate

```{r expt1_lmer1}
mss <- d %>%
  filter(t.crit >= 1 & t.crit <= 4) %>%
  filter(age_group != "adult") %>%
  filter(expt == "1") %>%
  group_by(trial_type, age_group, subid, item) %>%
  summarise(correct = mean(correct, na.rm = TRUE))

mss$subid <- factor(mss$subid)
mss$age_group <- as.numeric(as.character(mss$age_group)) # age as continuous
mss$trial_type <- relevel(mss$trial_type, "cs")
```

### plot

```{r expt1_lmer1_plot}
# plot
ms <- mss %>%
  group_by(trial_type, age_group, subid) %>%
  summarise(correct = mean(correct, na.rm = TRUE))

qplot(age_group, correct, col=trial_type, data=ms) + 
  geom_hline(yintercept=.5,lty=2) + 
  geom_smooth(method="lm")
```

### model 

```{r expt1_lmer1_model}
# lmer
simp.lm <- lmer(correct ~ age_group * trial_type 
                + (trial_type | subid) + (age_group + trial_type | item), # (age_group + trial_type | item) fails to converge
                data=mss)
summary(simp.lm)
```

# Experiment 2

## lmer: effect of trial type, age, and window on accuracy in Expt 2 

```{r expt2_lmer3}
##Experiment 2: prosody
#aggregate data across subjects and items
mss <- d %>%
  filter(age_group == "3" | age_group == "4") %>%
  filter(age_group != "2" & age_group != "5" & age_group != "adult") %>%
  filter(expt == "2") %>%
  filter(t.crit > 1 & t.crit <= 4.2) %>%
  # mutate(window = ifelse(t.crit > 1 & t.crit <= 2.6, "early", "late")) %>%
  group_by(trial_type, age_group, subid, item) %>%
  summarise(correct = mean(correct, na.rm = TRUE))

mss$subid <- factor(mss$subid)
mss$age_group <- as.factor(mss$age_group)
mss$trial_type <- relevel(mss$trial_type, "cs")
```

### plot

```{r expt2_lmer3_plot}
ms <- mss %>%
  group_by(trial_type, age_group, subid) %>%
  summarise(correct = mean(correct, na.rm = TRUE))

qplot(age_group, correct, col=trial_type, data=ms) + 
  # facet_wrap(~window) +
  geom_hline(yintercept=.5,lty=2) +
  geom_smooth(method="lm", aes(group=trial_type))
```

### model

```{r expt2_lmer3_model}
simp.lm <- lmer(correct ~ age_group * trial_type
                + (1 | subid) + (age_group | item), 
                data=mss)
summary(simp.lm)

```


## lmer: effect of age and window in inf trials in Expt 1 and 2 (Table 4)

```{r expt2_lmer4}
mss <- d %>%
  filter(age_group == "3" | age_group == "4") %>%
  filter((expt == "1" & t.crit > .78 & t.crit <= 3.62) |
           (expt == "2" & t.crit > 1.16 & t.crit <= 4)) %>%
  filter(trial_type == "inf") %>%
  mutate(window = ifelse(expt =="1",
    ifelse(t.crit > .78 & t.crit <= 2.2, "early", "late"), ifelse(t.crit > 1.16 & t.crit <= 2.58, "early", "late"))) %>%
  group_by(expt, trial_type, age_group, window, subid, item) %>%
  summarise(correct = mean(correct, na.rm = TRUE))

mss$subid <- factor(mss$subid)
mss$expt <- factor(mss$expt)
mss$age_group <- as.factor(mss$age_group) # age as factor
mss$trial_type <- relevel(mss$trial_type, "cs")
```

### plot 

```{r expt2_lmer4_plot}
ms <- aggregate(correct ~ expt + age_group + window + subid, mss, mean)
levels(ms$expt) <- c("Expt 1", "Expt 2")
qplot(window, correct, col=age_group, data=ms) + 
  facet_grid(expt~age_group) +
  geom_hline(yintercept=.5,lty=2) +
  geom_smooth(method="lm", aes(group=1))
```

### model

```{r expt2_lmer4_model}
simp.lm <- lmer(correct ~ expt * age_group * window
                + (window | subid) + (expt + age_group | item), # more complex random effects fail to converge
                data=mss)
summary(simp.lm)

```


Without window as a factor

```{r expt2_lmer5}
mss <- d %>%
  filter(age_group == "3" | age_group == "4") %>%
  filter((expt == "1" & t.crit > .78 & t.crit <= 3.62) |
           (expt == "2" & t.crit > 1.16 & t.crit <= 4)) %>%
#  filter(trial_type == "inf") %>%
#  mutate(window = ifelse(expt =="1",
#    ifelse(t.crit > .78 & t.crit <= 2.2, "early", "late"), ifelse(t.crit > 1.16 & t.crit <= 2.58, "early", "late"))) %>%
  group_by(expt, trial_type, age_group, subid, item) %>%
  summarise(correct = mean(correct, na.rm = TRUE))

mss$subid <- factor(mss$subid)
mss$expt <- factor(mss$expt)
mss$age_group <- as.factor(mss$age_group) # age as factor
mss$trial_type <- relevel(mss$trial_type, "cs")
```

```{r expt2_lmer5_model}

# looking at all trial types
simp.lm <- lmer(correct ~ expt * age_group * trial_type
                + (trial_type | subid) + (expt + age_group + trial_type | item), 
                data=mss)
summary(simp.lm)

# looking at just inf trials
simp.lm <- lmer(correct ~ expt * age_group
                + (1 | subid) + (expt + age_group | item), 
                data=subset(mss, trial_type == "inf"))
summary(simp.lm)
```

